name: Terraform Workflow

on:
    push:
      branches: [ "main" ] # Executa quando um commit é feito na branch main
    pull_request:
      branches: [ "main" ] # Executa quando um pull request é aberto na branch main
    schedule:
      - cron: '0 9 * * *' # Executa todos os dias às 9h UTC

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.3  # Especifica a versão do Terraform

    - name: Install Graphviz
      run: sudo apt-get update && sudo apt-get install -y graphviz

    - name: Terraform Init
      run: terraform init --upgrade

    - name: Generate Terraform Graph DOT file
      run: terraform graph > graph.dot

    - name: Check DOT file content
      run: cat graph.dot

    - name: Convert DOT to PNG
      run: dot -Tpng graph.dot -o graph.png

    - name: Upload Terraform Graph
      uses: actions/upload-artifact@v3
      with:
        name: terraform-graph
        path: graph.png